server:
 port: 8081

topic:
 name: "KafkaDemo-AVRO-Topic"

spring:
 kafka:
  properties:
   value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
   schema.registry.url: http://localhost:8081
   specific.avro.reader: true
  consumer:
   bootstrap-servers: "127.0.0.1:9092"
   key-deserializer:    org.apache.kafka.common.serialization.StringDeserializer
   value-deserializer:  io.confluent.kafka.serializers.KafkaAvroDeserializer
   group-id: "demo-avro-consumer-group"